name: CI

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  build:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]
        include:
          - node: 18
            experimental: false
          - node: 20
            experimental: false
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Test with coverage
        run: pnpm run test:coverage

      - name: Build
        run: pnpm run build

      - name: Upload coverage to Codecov
        if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request') }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
